//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public AppUser()
        {
            this.Stat = new HashSet<Stat>();
            this.Team = new HashSet<Team>();
        }
    
        public System.Guid UserId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public int Age { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Stat> Stat { get; set; }
        public virtual ICollection<Team> Team { get; set; }
    }
}
