//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimonOMarcusEntities : DbContext
    {
        public SimonOMarcusEntities()
            : base("name=SimonOMarcusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Stat> Stat { get; set; }
        public DbSet<AppUser> AppUser { get; set; }
        public DbSet<Team> Team { get; set; }
    }
}
